### ISSUE TITLE
Not really an issue

### ISSUE THREAD

**Issue by nihalkenkre** [jzharris/Unity-MNIST#1]
yours is the first unity - tfsharp example i came across. thank you for getting me going.

I am trying to classify images through unity. Need your input on the following.

How would you change this line for an input image of dimension 128 x 64 (width x height).

https://github.com/jzharris/Unity-MNIST/blob/e9a4fd5855f5a034e0c35c6bc794460ba732a119/Unity-Files/MNIST/Assets/Scripts/MNIST_Classifier.cs#L56

Thank you,
Nihal

**Comment by jzharris** [comment]
Hello Nihal,

I have clarified which operations use the image's width vs. height. Please pull commit 1e088b3b4c6d7e93f498d92d5aa115cb309f4640 and verify that the classifier output is what you expect.

**Comment by nihalkenkre** [comment]
Thank you for the clarification. 

I have yet to pull.

Could you please explain the need for this kind of index access.

**Comment by nihalkenkre** [comment]
FYI. 

I have trained my own model, in numpy arrays created from opencv images. The CV.imread, resize, and then np.asarray path

**Comment by jzharris** [comment]
You are correct, my method was very complicated. I propose a simpler solution in the latest commit, a54f25097e1244e5b1dcf52768e596aac310a833.

Unity has no way of converting an image texture to an array of pixel values, so I loop through the input texture and copy each value into the array one pixel at a time.

**Comment by nihalkenkre** [comment]
Hello,

Thank you for making the code simpler to read.

could you elaborate the need to do this
inputImg [0, img_width - i - 1, j, 0] = input.GetPixel(j, i).r;

rather than 

inputImg [0, i, j, 0] = input.GetPixel(i, j).r;

-----
Nihal

**Comment by nihalkenkre** [comment]
Just tried the changes, the results are not accurate, with probabilities around 25%.

I am guessing the input data order in C# would depend on how the model training input data has been provided.

while this solution would work with the MNIST data, it might not work for other trained models.

I would need to double check on that.

**Comment by nihalkenkre** [comment]
```c#
float[,,,] img = new float[1, imageHeight, imageWidth, 1];

for (int y = imageHeight - 1; y >= 0; y--) {
    for (int x = imageWidth - 1; x >= 0; x--) {
        img[0, imageHeight - y - 1, x, 0] = texture.GetPixel (x, y).r;
    }
}
```

This is working for my case.

Thank you Zach!!!
